select remito.id,
remito.id_tipo_remito,
remito.fecha,
remito.punto_venta,
remito.numero,
remito.id_forma_pago,
remito.id_usuario,
remito.monto,
remito.id_cliente,
remito.id_site,
remito.id_contrato,
remito.id_referencia,
remito.id_estado,
remito.fecha_creacion,
remito.archivo,
remito.archivo_url,
remito.facturado,
remito_detalle.id,
remito_detalle.id_remito,
remito_detalle.id_activo,
remito_detalle.precio_unit,
remito_detalle.precio_tot,
remito_detalle.divisa,
remito_detalle.cantidad,
remito_detalle.item,
activo.codigoNew,
activo.id_rubro,
activo.id_subrubro,
activo.desc_larga,
contrato.id,
contrato.id_cliente,
contrato.numero,
contrato.fecha,
contrato.fecha_inicio,
contrato.fecha_fin,
contrato.id_divisa,
contrato.monto,
contrato.porcentaje,
contrato_detalle.id,
contrato_detalle.id_contrato,
contrato_detalle.posicion,
contrato_detalle.descripcion,
contrato_detalle.id_subrubro,
contrato_detalle.id_divisa,
contrato_detalle.precio,
contrato_detalle.porcentaje,
contrato_detalle.id_unidad
from 
    (remito join (remito_detalle join activo on activo.id = remito_detalle.id_activo ) on remito_detalle.id_remito = remito.id) 
    join 
    (contrato join contrato_detalle on contrato_detalle.id_contrato = contrato.id )
     on remito.id_contrato = contrato.id
where id_remito = 1;