select remito.id,
remito.id_tipo_remito,
remito.fecha,
remito.punto_venta,
remito.numero,
remito.id_forma_pago,
remito.id_usuario,
remito.monto,
remito.id_cliente,
remito.id_site,
remito.id_contrato,
remito.id_referencia,
remito.id_estado,
remito.fecha_creacion,
remito.archivo,
remito.archivo_url,
remito.facturado,
remito.id,
remito.id_remito,
remito.id_activo,
remito.precio_unit,
remito.precio_tot,
remito.divisa,
remito.cantidad,
remito.item,
activo.codigoNew,
activo.id_rubro,
activo.id_subrubro,
activo.desc_larga,
contrato.id,
contrato.id_cliente,
contrato.numero,
contrato.fecha,
contrato.fecha_inicio,
contrato.fecha_fin,
contrato.id_divisa,
contrato.monto,
contrato.porcentaje,
contrato.id,
contrato.id_contrato,
contrato.posicion,
contrato.descripcion,
contrato.id_rubro,
contrato.id_clase,
contrato.id_subrubro,
contrato.id_activo,
contrato.id_divisa,
contrato.precio,
contrato.porcentaje,
contrato.id_unidad
from 
    (remito inner join (remito_detalle inner join activo on activo.id = remito_detalle.id_activo )on remito_detalle.id_remito = remito.id) 
    inner join 
    (contrato inner join contrato_detalle on contrato_detalle.id_contrato = contrato.id )
     on remito.id_contrato = contrato.id
where id_remito = 1;